---
# tasks file for Hadoop_Client
- name: "Uploading  hadoop Software..."
  copy:
    src: "./hadoop-1.2.1-1.x86_64.rpm"
    dest: "/root/hadoop.rpm"
  run_once: True

- name: "Uploading jdk Software..."
  copy:
    src: "./jdk-8u171-linux-x64.rpm"
    dest: "/root/jdk.rpm"
  run_once: True

- name: "Installing JDK..."
  shell:
    cmd: "rpm -ivh /root/jdk.rpm"
  ignore_errors: yes

- name: "Installing Hadoop Software..."
  shell:
    cmd: "rpm -ivh --force /root/hadoop.rpm"
  ignore_errors: yes

- name: "Changing Core File..."
  template:
    src: "core-client.txt"
    dest: "/etc/hadoop/core-site.xml"

- name: "Changing mapred file..."
  template:
    src: "mapred-client.txt"
    dest: "/etc/hadoop/mapred-site.xml"

- name: "Making system file executable..."
  file:
    path: "/etc/rc.d/rc.local"
    mode: u=rwx,g=rx,o=rx


