---
- hosts: localhost
  tasks:
  vars_files:
  - nodes.txt
  tasks:
  - name: "Provisioning Jobtracker..."
    ec2:
      key_name: "{{key}}"
      instance_type: "{{type_instance}}"
      image: "{{image_id}}"
      count: 1
      region: "{{region_name}}"
      assign_public_ip: yes
      instance_tags:
          Name: Jobtracker
      group_id: "{{security_grp_id}}"
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      state: present
      wait: yes
      vpc_subnet_id: "{{subnet_id}}"

