---
- name: "LocalHost WOrking..."
  hosts: localhost
  tasks:
#  - name: "Python Module Installing..."
#    shell:
#      cmd: "pip3 install gdown"

#  - name: "Downloading hadoop Software..."
#    shell:
#      cmd: "gdown --id 1l4Mv2ngXMacO_Cvaqw2SEh0qIi9q7Zl_"
#    run_once: True

#  - name: "Downloading jdk Software..."
#    shell:
#      cmd: "gdown --id 1KV7l0ApxLEWR7vu_P3ovFJdCS1XExq5q"
#    run_once: True

  - name: "Variable File Sharing..."
    shell:
      cmd: "cat ../temp/jobtracker_ip.txt"
    register: "jt_ip"

  - name: "Jobtracker IP storing..."
    lineinfile:
      path: "../Hadoop_Tasktracker/vars/main.yml"
      line: "{{ jt_ip.stdout }}"


  - name: "Check"
    debug:
      msg: "It'll work"


- name: "Tasktracker Configuring..."
  hosts: tag_Name_Tasktracker
  roles:
  - role: "Hadoop_Tasktracker"

